# DB config
# Primary Database (Main)
spring.datasource.main.url=${SPRING_DATASOURCE_MAIN_URL}
spring.datasource.main.username=${SPRING_DATASOURCE_MAIN_USERNAME}
spring.datasource.main.password=${SPRING_DATASOURCE_MAIN_PASSWORD}
spring.datasource.main.driver-class-name=org.postgresql.Driver
# spring.datasource.main.hikari.maximum-pool-size=10
# Secondary Database (Analysis)
spring.datasource.analysis.url=${SPRING_DATASOURCE_ANALYSIS_URL}
spring.datasource.analysis.username=${SPRING_DATASOURCE_ANALYSIS_USERNAME}
spring.datasource.analysis.password=${SPRING_DATASOURCE_ANALYSIS_PASSWORD}
spring.datasource.analysis.driver-class-name=org.postgresql.Driver
# spring.datasource.analysis.hikari.maximum-pool-size=5
# =======================
# Kafka Base Config
# =======================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# =======================
# Email Configuration
# =======================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
# =======================
# Admin
# =======================
spring.kafka.admin.properties.bootstrap.servers=${18.140.152.234:localhost:9092}
# =======================
# Logging
# =======================
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN
logging.level.com.moviestreaming=DEBUG